name: Poetry Update

on:
  # Run weekly on Monday at 0700AM
  schedule:
    - cron: "0 7 * * MON"
  # Allow a manual trigger
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
        - uses: fuzzylabs/gha-poetry-update@v1
          with:
            python-version: "3.10"
