name: Pre-commit autoupdate

on:
  # Run weekly on Monday at 0700AM
  schedule:
    - cron: "0 7 * * MON"
  # Allow a manual trigger
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run pre-commit autoupdate
        uses: fuzzylabs/pre-commit-autoupdate-action@v1
        with:
          python-version: "3.10"
